[package]
name = "tpscube"
version = "0.1.0"
authors = ["Rusty Wagner <rusty.wagner@gmail.com>"]
edition = "2021"

[[bin]]
name = "tpscube"
path = "src/main.rs"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
egui = "0.31"
eframe = { version = "0.31", default-features = false, features = ["wgpu"], optional = true }
tpscube_core = { path = "lib", default-features = false }
getrandom = "0.2"
instant = "0.1"
anyhow = "1.0"
chrono = "0.4"
gl_matrix = "0.0"
num-traits = "0.2"
image = { version = "0.25", default-features = false, features = ["png"] }
wgpu = { version = "24", optional = true }
egui-wgpu = { version = "0.31", optional = true }
bytemuck = { version = "1.0", features = ["derive"] }
pollster = "0.3"
log = "0.4"
env_logger = "0.10"

[features]
default = ["tpscube_core/native-storage", "tpscube_core/bluetooth", "wgpu-backend"]
wasm = ["wgpu-backend", "getrandom/js", "tpscube_core/web-storage", "tpscube_core/web-bluetooth", "instant/wasm-bindgen", "chrono/wasmbind"]
wgpu-backend = ["eframe", "wgpu", "egui-wgpu"]

[profile.dev]
opt-level = 2

[profile.release]
panic = "abort"

[target.'cfg(target_arch="wasm32")'.dependencies]
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
js-sys = "0.3"

[target.'cfg(target_arch="wasm32")'.dependencies.web-sys]
version = "0.3"
features = [
  "Clipboard",
  "ClipboardEvent",
  "CompositionEvent",
  "console",
  "CssStyleDeclaration",
  "DataTransfer",
  "Document",
  "DomRect",
  "Element",
  "Event",
  "EventListener",
  "EventTarget",
  "FocusEvent",
  "HtmlCanvasElement",
  "HtmlElement",
  "HtmlInputElement",
  "InputEvent",
  "KeyboardEvent",
  "Location",
  "MediaQueryList",
  "MouseEvent",
  "Navigator",
  "Performance",
  "Storage",
  "Touch",
  "TouchEvent",
  "TouchList",
  "WebGl2RenderingContext",
  "WebGlBuffer",
  "WebGlProgram",
  "WebGlRenderingContext",
  "WebGlShader",
  "WebGlTexture",
  "WebGlUniformLocation",
  "WheelEvent",
  "Window",
]

[target.'cfg(not(target_arch="wasm32"))'.dependencies]
tinyfiledialogs = "3.8"
tokio = { version = "1.7", features = ["full"] }
keepawake = "0.6"
